add_lunch_combo hazy_bacon-userdebug
add_lunch_combo hazy_find7-userdebug
add_lunch_combo hazy_m8-userdebug
add_lunch_combo hazy_shamu-userdebug
add_lunch_combo hazy_hammerhead-userdebug
add_lunch_combo hazy_mako-userdebug
add_lunch_combo hazy_i9300-userdebug