#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t hazy"

$L "        ___   ___       ";
$L "|___|  |___|    /   \_/ ";
$L "|   |  |   |  _/_    |  ";
$L "Welcome to Android `getprop ro.build.version.release` / HazyRom-`getprop ro.hazy.version`";
